# -*- coding: utf-8 -*-
"""gestao portuaria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fxuSt7v2aHkdtb_8uhb3J828fTSLocJI
"""

import pandas as pd
import numpy as np
import random

# Definindo parâmetros básicos
portos = ['Porto de Santos', 'Porto de Itaguaí', 'Porto de Suape', 'Porto de Paranaguá', 'Porto de Manaus']
tipos_carga = ['Granel Sólido', 'Granel Líquido', 'Conteinerizada', 'Carga Geral', 'Carga Viva']
origens = ['China', 'Estados Unidos', 'Brasil', 'Alemanha', 'Argentina']
destinos = ['África do Sul', 'Brasil', 'Reino Unido', 'México', 'Espanha']

# Gerando dados fictícios
def gerar_dados_portuarios(n_registros=100):
    dados = {
        'ID_Navio': [f'NAV{1000+i}' for i in range(n_registros)],
        'Porto': [random.choice(portos) for _ in range(n_registros)],
        'Tipo_Carga': [random.choice(tipos_carga) for _ in range(n_registros)],
        'Peso_Toneladas': np.random.randint(500, 50000, n_registros),
        'Tempo_Atracacao_horas': np.random.randint(8, 120, n_registros),
        'Origem': [random.choice(origens) for _ in range(n_registros)],
        'Destino': [random.choice(destinos) for _ in range(n_registros)],
        'Data_Chegada': pd.date_range(start='2024-01-01', periods=n_registros, freq='D')
    }
    df = pd.DataFrame(dados)
    df['Eficiência_Operacional'] = np.round(df['Peso_Toneladas'] / df['Tempo_Atracacao_horas'], 2)
    return df

# Gerar e visualizar os dados
df_porto = gerar_dados_portuarios(100)
print(df_porto.head())